# go-ecommerce-backend-api/configs/local.yaml
server:
  port: 8085

dbmysql:
  host: localhost
  port: 3307
  username: thinh
  password: secret
  dbname: ecommerce
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

logger:
  logLevel: debug
  fileLogName: logs/app.log
  maxSize: 10
  maxBackups: 3
  maxAge: 7
  compress: true